name: challange

on:
        schedule:
                - cron: '40 12 * * *'

jobs: 
        job1:
                name: First job
                runs-on: ubuntu-latest
                steps:
                        - name: Print the date
                          run: date
        job2: 
                name: Second job
                runs-on: windows-latest
                steps: 
                        - name: Print the date
                          run: echo %date:~-4%%date:~3,2%%date:~0,2%%time:~0,2%%time:~3,2%%time:~6,2% 
        job3:
                name: Third job
                runs-on: macos-latest
                steps:
                        - name: Print the date
                          run: Date
        job4:
                name: Fourth job
                runs-on: ubuntu-latest
                steps:
                        - name: Print the date in second ubuntu
                          run: date
                needs: [job1, job2, job3]
