name: first

on: push

jobs:
        job1:
                name: First job
                runs-on: ubuntu-latest
                steps:
                - name: Task one
                  uses: actions/checkout@v2
                - name: Task two
                  run: env | sort
        job2:
                name: Second job
                runs-on: windows-latest
                steps:
                - name: Task one
                  uses: actions/checkout@v2
                - name: Task two
                  run: "Get-ChildItem Env: | Sort-Object Name"

